apiVersion: apps/v1
kind: Deployment
metadata:
  name: spafolio-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spafolio
  template:
    metadata:
      labels:
        app: spafolio
        tier: backend
        version: v1
    spec:
      containers:
      - image: 676894/spafolio
        name: server
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
        resources:
            requests:
                cpu: 100m
                memory: 64Mi
            limits:
                cpu: 200m
                memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spafolio-srv
spec:
  selector:
    app: spafolio
  ports:
  - port: 3000
    targetPort: 3000
    name: http
       


