apiVersion: apps/v1
kind: Deployment
metadata:
  name: spafolio-version-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spafolio
  template:
    metadata:
      labels:
        app: spafolio
        tier: backend
        version: v1
    spec:
      containers:
      - image: 676894/spafolio:v1
        name: server
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spafolio-version-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spafolio
  template:
    metadata:
      labels:
        app: spafolio
        tier: backend
        version: v2
    spec:
      containers:
      - image: 676894/spafolio:v2
        name: server
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: spafolio-srv
spec:
  selector:
    app: spafolio
  ports:
  - port: 3000
    targetPort: 3000
    name: http
       


